language: cpp

compiler:
  - gcc

install:
 # g++4.8.1
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
 - sudo apt-get update -qq

install:
  # g++4.8.1
  - sudo apt-get install -qq g++-4.8;

  # Arduino lib
  - sudo apt-get install -qq arduino;

script:
  - ls
  - cd quad/
  - make
 
notifications:
  email:
    recipients:
      - romain.goussault@gmail.com
